name: Build Tweaks

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Tweaks
    runs-on: macos-latest

    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Install Dependencies
        run: brew install make ldid dpkg

      - name: Set PATH environment variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        id: theos
        uses: actions/cache@v4
        with:
          path: theos/
          key: theos-9bc73406cf80b711ef4d02c15ff1dedc4478a275

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: 9bc73406cf80b711ef4d02c15ff1dedc4478a275
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk "$THEOS/sdks"

      - name: Clone YouTubeHeader
        run: |
          if [ -d "$THEOS/include/YouTubeHeader" ]; then
            cd "$THEOS/include/YouTubeHeader" && git pull
          else
            cd "$THEOS/include"
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi

      - name: Clone PSHeader
        run: |
          if [ -d "$THEOS/include/PSHeader" ]; then
            cd "$THEOS/include/PSHeader" && git pull
          else
            cd "$THEOS/include"
            git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
          fi

      - name: Clone tweak repositories
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git
          git clone --quiet --depth=1 https://github.com/Tonwalter888/YTUHD.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouQuality.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoOverlay.git
          git clone --quiet --depth=1 https://github.com/therealFoxster/DontEatMyContent.git

      - name: Build tweaks
        run: |
          build() {
            cd "$1"
            make clean package DEBUG=0 FINALPACKAGE=1
            mv packages/*.deb ..
            cd ..
          }

          build YouPiP
          build YTUHD
          build Return-YouTube-Dislikes
          build YTABConfig
          build YouGroupSettings
          build YouQuality
          build YTVideoOverlay
          build DontEatMyContent

      - name: Clone Open in YouTube Safari Extension
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension
          cd OpenYoutubeSafariExtension
          git sparse-checkout set --no-cone OpenYoutubeSafariExtension.appex
          git checkout
          mv *.appex ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-debs
          path: |
            *.deb
            *.appex
          if-no-files-found: ignore

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build #${{ github.run_number }}
          generate_release_notes: true
          files: |
            *.deb
            *.appex
